pipeline:
  name: uno_pipe
  identifier: uno_pipe
  projectIdentifier: Harness_hands_on_project_for_Infosys_team
  orgIdentifier: InfyPOC
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: gitSangeeth
        build: <+input>
  stages:
    - stage:
        name: build_app
        identifier: build_app
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          caching:
            enabled: true
            override: true
          infrastructure:
            type: KubernetesDirect
            spec:
              connectorRef: kubeHarness
              namespace: harness-delegate-ng
              automountServiceAccountToken: true
              nodeSelector: {}
              os: Linux
          execution:
            steps:
              - step:
                  type: Run
                  name: code compile
                  identifier: code_compile
                  spec:
                    connectorRef: docker_quickstart
                    image: python:3.10.6-alpine
                    shell: Sh
                    command: python -m compileall ./
              - step:
                  type: BuildAndPushDockerRegistry
                  name: create_image
                  identifier: create_image
                  spec:
                    connectorRef: docker_quickstart
                    repo: hteegnas/samplerepo
                    tags:
                      - <+pipeline.sequenceId>
        when:
          pipelineStatus: Success
    - stage:
        name: deploy
        identifier: deploy
        description: ""
        type: Deployment
        spec:
          deploymentType: Kubernetes
          service:
            serviceRef: sangeeth_service
            serviceInputs:
              serviceDefinition:
                type: Kubernetes
                spec:
                  artifacts:
                    primary:
                      primaryArtifactRef: <+input>
                      sources: <+input>
          environment:
            environmentRef: dev
            gitBranch: main
            deployToAll: false
            infrastructureDefinitions:
              - identifier: dev
          execution:
            steps:
              - step:
                  name: Rollout Deployment
                  identifier: rolloutDeployment
                  type: K8sRollingDeploy
                  timeout: 10m
                  spec:
                    skipDryRun: false
                    pruningEnabled: false
            rollbackSteps:
              - step:
                  name: Rollback Rollout Deployment
                  identifier: rollbackRolloutDeployment
                  type: K8sRollingRollback
                  timeout: 10m
                  spec:
                    pruningEnabled: false
        tags: {}
        failureStrategies:
          - onFailure:
              errors:
                - AllErrors
              action:
                type: StageRollback
        delegateSelectors:
          - kubernetes-delegate-sangeeth
        when:
          pipelineStatus: Success
